import Head from "next/head";
import RSVP from "../components/rsvp";

export default function Home() {
  return (
    <div className="px-4 py-10 max-w-3xl mx-auto sm:px-6 sm:py-12 lg:max-w-4xl lg:py-16 lg:px-8 xl:max-w-6xl">
      <Head>
        <title>Going Away BBQ | Ashley & Ian</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@700&family=Libre+Franklin:ital,wght@1,400&family=Fira+Code&family=Newsreader&family=Playfair+Display:wght@800&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className="px-2 py-5 lg:px-4 lg:py-6 prose prose-sm sm:prose lg:prose-lg xl:prose-2xl mx-auto border-4 border-white rounded-lg bg-white filter drop-shadow shadow-xl">
        <div className="">
          <div>
            <span className="font-sans">you're invited to...</span>
            <h1 className="from-pink-400 to-indigo-800 text-center">
              Ashley & Ian's
              <br />
              Going Away BBQ
            </h1>

            <h2>What is this all about?</h2>
            <p>
              We are moving to <em>Denver!</em>
            </p>
            <p>
              We would like friends and family to join us for a casual
              get-together at our apartment complex.
            </p>
            <p>We will have:</p>
            <ul>
              <li>Burgers</li>
              <li>Brews</li>
              <li>Chips</li>
            </ul>

            <h2>Date & time</h2>
            <p>
              Saturday, August 7, 2021
              <br />
              4:00 - 8:00
            </p>

            <h2>Location & parking</h2>
            <div>
              <p>
                We will be hosting on our complex's patio at{" "}
                <strong>1415 Cuming Street</strong> on the south-side of the
                building. There is metered parking surrounding the building, and
                there is <em>unmetered</em> parking across Cuming Street to the
                north along 14<sup>th</sup> Street.
              </p>
              <div className="aspect-w-16 aspect-h-9">
                <iframe
                  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2998.892173721146!2d-95.93709798457793!3d41.26768357927535!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x87938fb60ddc971f%3A0x96eba0e6955d8c9b!2s1415%20Cuming%20St%2C%20Omaha%2C%20NE%2068102!5e0!3m2!1sen!2sus!4v1627473223609!5m2!1sen!2sus"
                  allowfullscreen=""
                  loading="lazy"
                  className="w-full h-full object-center object-cover lg:w-full lg:h-full rounded-lg"
                ></iframe>
              </div>
            </div>

            <h2>RSVP</h2>
            <RSVP />
          </div>
        </div>
      </main>

      <footer className="prose lg:prose-xl prose-indigo text-center mx-auto">
        <p className="font-mono text-indigo-400">made with ♥ by ian & ashley</p>
      </footer>
    </div>
  );
}
